import { botConfig } from '../structures/bot-config';
const whatsappID = "@lid"

export default {
  onlyGroupsMessage: '❕ Meus comandos só estão disponíveis para o uso em grupos!',
  noArgsErrorMessage: '❌ Você não forneceu os argumentos necessários para este comando!',
  invalidArgumentsErrorMessage: '❌ Você forneceu argumentos de tipos inválidos para este comando!',
  commandNotFoundErrorMessage: '❌ Este comando não foi encontrado!',
  noResponseErrorMessage: '❌ Você não forneceu respostas!',
  insufficientPermissionErrorMessage: '❌ Você não possui permissão para isto!',
  invalidYoutubeUrl: '❌ URL de vídeo inválida!',
  genericErrorMessage: (config: typeof botConfig, error: Error) => `> ❌ Erro Interno\nReporte ao meu desenvolvedor!_\n\nClique aqui:\nhttps://wa.me/${config.developer.number}?text=${encodeURIComponent(`Erro (${new Date().toISOString()})\n${error.message}`)}`,
  gettingVideoInfo: "🔍 Obtendo informações do vídeo...",
  tooLargeVideoSizeErrorMessage: (totalSize: number, sizeLimit: number) => `❌ O vídeo é muito grande (${(totalSize / (1024 * 1024)).toFixed(2)} MB). Limite: ${sizeLimit / (1024 * 1024)} MB.`,
  tooLargeVideoDurationErrorMessage: (totalDuration: number, durationLimit: number) => `❌ O vídeo é muito longo (${Math.floor(totalDuration / 60)} minutos). Limite: ${Math.floor(durationLimit / 60)} minutos.`,
  initializingVideoDownload: (title: string) => `> ${title}\n\n⏬ Iniciando download...`,
  videoDownloadProgress: (percent: number) => `📥 Baixando: ${percent}%`,
  successVideoDownload: "✅ Download concluído! Enviando vídeo...",
  earnedXp: (amount: number) => `✨ Você ganhou *${amount} xp*!`,
  insufficientMoney: '💔 Você não tem estrelas o suficiente',
  explorationSuccess: (stars: number, xp: number) => `🎉 Você encontrou um tesouro!\n> Estrelas: *+${stars} 🌟*\n> XP: *+${xp} ⚗️*`,
  explorationFailure: (stars: number, xp: number) => `🔻 Você gastou recursos e não achou nada!\n> Estrelas: *-${stars} 🌟*\n> XP: *+${xp} ⚗️*`,
  playerLevelUp: '🆙 *Parabéns!*\n> Você acaba de subir um nível!',
  foundItem: (itemName: string) => `🕵🏻‍♀️ Você encontrou um item: \`${itemName}\``,
  invalidPotionCombination: '💔👩🏻‍🔬 Essa combinação não resultou em nada!',
  successGeneratePotion: (potionName: string) => `👩🏻‍🔬 *Parabéns!*\nVocê obteve a poção: \`${potionName}\``,
  notFoundItemOnInventory: '💔👩🏻‍🔬 Você não possui esse item no inventário\n> Verifique o nome correto',
  successRobbery: (playerJid: string, stars: number) => `🥷🏻 Você acaba de roubar o jogador: @${playerJid.replace(whatsappID, '')}\n*Levou ${stars} 🌟!*`,
  failRobbery: (playerJid: string) => `🛡️Você tentou roubar o jogador: @${playerJid.replace(whatsappID, '')} e falhou!`,
  everyoneLosesStars: (playerName: string, stars: number) => `👩🏻‍🔬🧪  *${playerName}* utilizou uma poção e todos perderam estrelas!\n> Estrelas: -${stars} 🌟  (exceto ${playerName})`,
  removeAllEffects: '👩🏻‍🔬🧪 Efeitos removidos com sucesso!',
  addEffect: (playerName: string) => `👩🏻‍🔬🧪 *${playerName}* utilizou uma poção e obteve efeitos!`,
  alreadyHasEffectActivated: '👩🏻‍🔬 Você já está sob um efeito!\n> Livre-se do efeito atual primeiro',
  potionUsedInPlayer: (playerJid: string) => `👩🏻‍🔬🧪 Você usou uma poção no jogador: @${playerJid.replace(whatsappID, '')}`,
  shopItemNotFound: '❌ Este item não foi encontrado na loja.',
  alreadyHasItem: '❌ Já possui este item no inventário.',
  successBuyItem: (itemName: string) => `🎉 *Você realizou uma compra!*\n> Item: \`${itemName}\``,
  playerNotFound: '❌ Este jogador não foi encontrado ou não tem registros.',
  requiredMinimumLevel: (level: number) => `❌ Você precisa ter no mínimo o *Nível ${level}!*`,
  requiredWeaponEquipped: '🗡️ Equipe uma arma para usar isto!',
  attackedPlayer: (playerJid: string, hp: number) => `🗡️ Você acaba de atacar o jogador: @${playerJid.replace(whatsappID, '')}\n*Causou ${hp} 🔺 de dano!*`,
  playerDead: (playerJid: string) => `💀 O Jogador @${playerJid.replace(whatsappID, '')} morreu!\n> Perdeu todos os itens!`,
  successEquipItem: (itemName: string) => `🪖 *Você equipou um item!*\n> Item: \`${itemName}\``,
  successHpRecover: (hp: number) => `💕 *Vida restaurada*\n> Curou \`${hp} pontos de vida.\``,
  alreadyHasFullHp: `👩🏻‍🔬🧪 Sua vida já está cheia!`,
  notFoundAnyItem: '[❗] Item inválido!\n> Verifique o nome correto',
};
