export default {
  noArgsErrorMessage: '*[❕] Utilize algum argumento!*',
  invalidArgumentsErrorMessage: '*[❕] Argumento de tipo inválido!*',
  invalidPlayerClass: '*[❕] Classe de jogador incompatível!*',
  commandNotFoundErrorMessage: '*[❕] Comando inexistente!*',
  noResponseErrorMessage: '*[❕] Sem resposta!*',
  insufficientPermissionErrorMessage: '*[❕] Sem permissão para isso!*',
  genericErrorMessage: '*[❗] Ocorreu um erro.*',
  insufficientMoney: '*[❕] Estrelas insuficientes.*',
  notFoundItemOnInventory: '*[❕] Você não possui esse item!*',
  shopItemNotFound: '*[❕] Item não encontrado na loja.*',
  alreadyHasItem: '*[❕] Já possui este item!*',
  successBuyItem: (itemName: string) => `*[🎉] Você realizou uma compra!*\n> Item: \`${itemName}\``,
  successEquipItem: (itemName: string) => `*[🪖] Você equipou um item!*\n> Item: \`${itemName}\``,
  successSkinChanged: (skinName: string) => `*[🥻] Skin alterada!*\n> Skin: \`${skinName}\``,
  notFoundAnyItem: '*[❕] Item inválido!*',
  playerUnregistered: '*[❕] Registre-se para prosseguir.*',
  alreadyRegistered: '*[❕] Jogador já registrado.*',
  successRegister: '*[✅] Registrado com sucesso!*'
};
