export default [
    { type: 'madeira', category: 'resource', isSingle: true, value: 'Madeira' },
    { type: 'pedra', category: 'resource', isSingle: true, value: 'Pedra' },
    { type: 'carne', category: 'resource', isSingle: true, value: 'Carne' },
    { type: 'mineração', category: 'resource', isSingle: false, values: ['Gemas', 'Ouro', 'Ferro', 'Cobre', 'Estanho'] },
    { type: 'grãos', category: 'resource', isSingle: false, values: ['Trigo', 'Milho', 'Cevada', 'Arroz', 'Centeio', 'Aveia', 'Linhaça'] },
    { type: 'frutas', category: 'resource', isSingle: false, values: ['Melão', 'Pêssego', 'Maçã', 'Uva', 'Ameixa', 'Laranja', 'Romã'] },
    { type: 'ervas', category: 'resource', isSingle: false, 
	    values:  [
    		"Campânula",
    		"Lótus preto",
    		"Flor de sangue",
    		"Coldsnaps",
    		"Respiração de dragão",
    		"Estrela da noite",
    		"Frostfires",
    		"Gillyflowers",
    		"Gengibre",
    		"Taça dourada",
    		"Renda de Donzela",
    		"Tojo",
    		"Lavanda",
    		"Hepáticas",
    		"Lilás",
    		"Espinhosa",
    		"Moonblom",
    		"Nightshade",
    		"Pennyroyal",
    		"Beijo venenoso",
    		"Papoula",
    		"Rosa escura",
    		"Rosa",
    		"Tarsy",
    		"Flor de especiarias",
    		"Cardo",
    		"Wolfsbane",
    		"Hortelã",
    		"Artemisia",
    		"Cânhamo",
    		"Regalsou",
    		"Erva flauta",
    		"Erva do diabo",
    		"Espectral",
    		"Fogo congelado",
    		"Lua florescente",
    		"Sequerella",
    		"Sanguinário",
    		"Vigier",
    		"Rubec",
    		"Fogo de ameixa",
    		"Pinho ordenado",
    		"Areia mangave",
    		"Hranna",
    		"Fumevinho",
    		"Dedal de bujarrona",
    		"Flor do ladrão",
    		"Aspidis"
	    ] },
];

